"use client";

import { useMemo, useState } from "react";

const programs = [
  { id:"pony", region:"서울", title:"포니 승마체험", dept:"공원화사업팀TF", price:5000, tone:"sun", icon:"♞", desc:"아이와 포니가 교감하는 즐거운 첫 승마" },
  { id:"tour-s", region:"서울", title:"렛츠런파크 투어", dept:"서울고객안전부", price:8000, tone:"green", icon:"◉", desc:"해설사와 만나는 경마공원의 숨은 이야기" },
  { id:"riding-b", region:"부산", title:"말과 함께 승마체험", dept:"부산시설부", price:7000, tone:"blue", icon:"♞", desc:"초보자도 안전하게 즐기는 승마 프로그램" },
  { id:"tour-b", region:"부산", title:"말 테마파크 투어", dept:"부산고객지원부", price:6000, tone:"coral", icon:"◎", desc:"말의 생태와 문화를 따라 걷는 테마 투어" },
  { id:"pony-j", region:"제주", title:"제주마 승마체험", dept:"제주운영부", price:10000, tone:"purple", icon:"♞", desc:"제주 초원을 닮은 특별한 승마 경험" },
  { id:"tour-j", region:"제주", title:"목장 올레 투어", dept:"제주고객지원부", price:7000, tone:"mint", icon:"⌁", desc:"제주마와 초원을 가까이에서 만나는 산책" },
];
const slots = ["10:00", "11:00", "13:30", "14:30", "15:30"];
const bookings = [
 { no:"R260826-143021", when:"2026.08.30 10:00", booked:"08.26 14:30:21", customer:"김렛츠", phone:"010-12**-56**", program:"포니 승마체험", region:"서울", qty:2, amount:10000, status:"결제완료" },
 { no:"R260826-112408", when:"2026.08.30 13:30", booked:"08.26 11:24:08", customer:"이러닝", phone:"010-98**-10**", program:"렛츠런파크 투어", region:"서울", qty:4, amount:32000, status:"결제완료" },
 { no:"R260825-172219", when:"2026.08.29 14:30", booked:"08.25 17:22:19", customer:"박제주", phone:"010-34**-78**", program:"제주마 승마체험", region:"제주", qty:2, amount:20000, status:"이용완료" },
 { no:"R260825-090312", when:"2026.08.29 11:00", booked:"08.25 09:03:12", customer:"최부산", phone:"010-66**-22**", program:"말 테마파크 투어", region:"부산", qty:1, amount:6000, status:"취소완료" },
];

function money(n:number){ return new Intl.NumberFormat("ko-KR").format(n)+"원"; }

export default function Home(){
 const [mode,setMode]=useState<"customer"|"admin">("customer");
 const [region,setRegion]=useState("서울");
 const [selected,setSelected]=useState(programs[0]);
 const [step,setStep]=useState(1);
 const [slot,setSlot]=useState("10:00");
 const [qty,setQty]=useState(2);
 const [discount,setDiscount]=useState(false);
 const [adminTab,setAdminTab]=useState("대시보드");
 const [toast,setToast]=useState("");
 const [blocked,setBlocked]=useState<string[]>(["15:30"]);
 const [myTab,setMyTab]=useState("예정");
 const total=selected.price*qty*(discount?0.8:1);
 const visible=useMemo(()=>programs.filter(p=>p.region===region),[region]);
 const showToast=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const chooseProgram=(p:typeof programs[0])=>{setSelected(p);setStep(2);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className="app-shell">
  {toast&&<div className="toast" role="status">✓ {toast}</div>}
  <header className="topbar">
   <button className="brand" onClick={()=>{setMode("customer");setStep(1)}}><span className="brand-mark">L</span><span>LET&apos;S RUN <b>PLAY</b></span></button>
   <nav className="topnav" aria-label="주요 메뉴">
    <button className={mode==="customer"?"active":""} onClick={()=>{setMode("customer");setStep(1)}}>프로그램</button>
    <button onClick={()=>{setMode("customer");setStep(4)}}>나의 예약</button>
    <button className={mode==="admin"?"active":""} onClick={()=>setMode("admin")}>운영자</button>
   </nav>
   <div className="profile"><span className="avatar">김</span><span>김렛츠님</span></div>
  </header>
  {mode==="customer" ? <>
   {step===1&&<ProgramHome region={region} setRegion={setRegion} visible={visible} choose={chooseProgram}/>} 
   {step===2&&<Booking selected={selected} slot={slot} setSlot={setSlot} qty={qty} setQty={setQty} discount={discount} setDiscount={setDiscount} total={total} next={()=>setStep(3)}/>} 
   {step===3&&<Payment selected={selected} slot={slot} qty={qty} total={total} back={()=>setStep(2)} pay={()=>{setStep(5);showToast("결제가 완료되었습니다")}}/>}
   {step===4&&<MyPage tab={myTab} setTab={setMyTab} select={()=>setStep(5)} showToast={showToast}/>} 
   {step===5&&<Ticket selected={selected} slot={slot} qty={qty} total={total} home={()=>{setStep(1)}}/>}
  </> : <Admin tab={adminTab} setTab={setAdminTab} blocked={blocked} setBlocked={setBlocked} showToast={showToast}/>} 
 </main>
}

function ProgramHome({region,setRegion,visible,choose}:any){return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">LET&apos;S RUN PARK EXPERIENCE</span><h1>말과 함께,<br/><em>오늘을 특별하게</em></h1><p>서울·부산·제주 렛츠런파크의 승마체험과 투어를<br/>한 곳에서 편리하게 예약하세요.</p><div className="hero-meta"><span>✓ 간편한 모바일 티켓</span><span>✓ 이용 10분 전까지 취소</span></div></div><div className="horse-art" aria-hidden="true"><span className="sun-disc"></span><span className="horse">♞</span><span className="hill h1"></span><span className="hill h2"></span><i>PLAY!</i></div></section>
 <section className="content"><div className="section-head"><div><span className="kicker">PROGRAM</span><h2>어디에서 즐겨볼까요?</h2></div><div className="region-tabs">{["서울","부산","제주"].map(r=><button key={r} className={region===r?"selected":""} onClick={()=>setRegion(r)}>{r}</button>)}</div></div>
 <div className="program-grid">{visible.map((p:any)=><article className={`program-card ${p.tone}`} key={p.id}><div className="art"><span>{p.icon}</span><b>{p.region}</b></div><div className="card-body"><small>{p.dept}</small><h3>{p.title}</h3><p>{p.desc}</p><div className="card-foot"><strong>{money(p.price)} <small>/ 1인</small></strong><button onClick={()=>choose(p)}>예약하기 <span>→</span></button></div></div></article>)}</div>
 <div className="notice-strip"><b>예약 전 확인해주세요</b><span>예약은 오늘부터 2주 뒤까지 열려요.</span><span>1인 최대 4매까지 구매할 수 있어요.</span><span>현장 접수는 별도 재고로 운영돼요.</span></div></section>
 </>}

function Steps({now}:{now:number}){return <div className="steps">{["프로그램 선택","일정·인원","결제","예약 완료"].map((s,i)=><div className={now>i?"on":""} key={s}><span>{now>i+1?"✓":i+1}</span><b>{s}</b></div>)}</div>}
function Booking({selected,slot,setSlot,qty,setQty,discount,setDiscount,total,next}:any){return <div className="booking-page"><Steps now={2}/><div className="booking-layout"><section className="booking-main"><button className="back" onClick={()=>history.back()}>← 프로그램 다시 선택</button><h1>방문 일정을 선택해주세요</h1><p className="sub">선택한 프로그램 <b>{selected.region} · {selected.title}</b></p><div className="panel"><div className="panel-title"><h3>날짜 선택</h3><span>예약 가능 기간 08.26 — 09.09</span></div><div className="week"><b>2026년 8월</b><div className="days">{[26,27,28,29,30,31,1].map((d,i)=><button key={d} className={i===4?"pick":""}><small>{["수","목","금","토","일","월","화"][i]}</small><strong>{d}</strong>{i===4&&<i>선택</i>}</button>)}</div></div></div><div className="panel"><div className="panel-title"><h3>회차 선택</h3><span className="legend">● 예약가능　<span>● 마감임박</span></span></div><div className="slot-grid">{slots.map((s,i)=><button key={s} disabled={i===4} className={slot===s?"pick":""} onClick={()=>setSlot(s)}><b>{s}</b><small>{i===4?"마감":i===2?"2자리 남음":`${8-i}자리 남음`}</small></button>)}</div></div><div className="panel people"><h3>인원 선택</h3><div><span>일반 <small>1인 {money(selected.price)}</small></span><div className="counter"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(Math.min(discount?2:4,qty+1))}>＋</button></div></div><label><input type="checkbox" checked={discount} onChange={e=>{setDiscount(e.target.checked);if(e.target.checked&&qty>2)setQty(2)}}/> 과천시민 할인 적용 <small>20% 할인 · 최대 2매</small></label></div></section><aside className="summary"><div className={`mini-art ${selected.tone}`}>{selected.icon}</div><small>{selected.region} 렛츠런파크</small><h3>{selected.title}</h3><dl><div><dt>이용일</dt><dd>2026.08.30 (일)</dd></div><div><dt>회차</dt><dd>{slot}</dd></div><div><dt>인원</dt><dd>{qty}명</dd></div></dl><div className="total"><span>결제 예정 금액</span><strong>{money(total)}</strong></div><button className="primary" onClick={next}>결제하기</button><p className="safe">🔒 안전한 결제를 위해 토스페이먼츠로 이동합니다.</p></aside></div></div>}

function Payment({selected,slot,qty,total,back,pay}:any){return <div className="booking-page narrow"><Steps now={3}/><div className="pay-card"><button className="back" onClick={back}>← 일정 변경</button><h1>예약 내용을 확인해주세요</h1><div className="order-item"><div className={`mini-art ${selected.tone}`}>{selected.icon}</div><div><small>{selected.region} 렛츠런파크</small><h3>{selected.title}</h3><p>2026.08.30 (일) · {slot} · {qty}명</p></div><strong>{money(total)}</strong></div><section><h3>예약자 정보</h3><div className="info-row"><label>이름<input value="김렛츠" readOnly/></label><label>연락처<input value="010-1234-5678" readOnly/></label></div></section><section><h3>결제 수단</h3><div className="pay-methods"><button className="chosen">간편결제</button><button>신용·체크카드</button><button>계좌이체</button></div><div className="toss">toss <b>payments</b><span>간편하고 안전한 결제</span></div></section><label className="agree"><input type="checkbox" defaultChecked/> 예약 및 취소 규정과 개인정보 수집에 모두 동의합니다.</label><div className="pay-bottom"><div><small>최종 결제 금액</small><strong>{money(total)}</strong></div><button className="primary" onClick={pay}>{money(total)} 결제하기</button></div></div></div>}

function MyPage({tab,setTab,select,showToast}:any){return <div className="mypage"><div className="mypage-head"><span className="eyebrow">MY RESERVATION</span><h1>나의 예약</h1><p>김렛츠님, 다가오는 즐거운 경험을 확인하세요.</p></div><div className="my-tabs">{["예정","완료","취소"].map((t,i)=><button className={tab===t?"on":""} onClick={()=>setTab(t)} key={t}>{t}<span>{i===0?2:i===1?3:1}</span></button>)}</div>{tab==="예정"?<div className="reservation-list"><article><div className="date-box"><b>30</b><span>8월 · 일</span></div><div className="res-info"><span className="status">예약 확정</span><h3>포니 승마체험</h3><p>서울 렛츠런파크 · 10:00 · 2명</p><small>예약번호 R260826-143021</small></div><div className="res-actions"><button onClick={select}>티켓 보기</button><button onClick={()=>showToast("예약 취소 요청이 접수되었습니다")}>예약 취소</button></div></article><article><div className="date-box"><b>05</b><span>9월 · 토</span></div><div className="res-info"><span className="status">예약 확정</span><h3>렛츠런파크 투어</h3><p>서울 렛츠런파크 · 13:30 · 4명</p><small>예약번호 R260820-091425</small></div><div className="res-actions"><button>티켓 보기</button><button>예약 취소</button></div></article></div>:<div className="empty"><span>⌁</span><h3>{tab}된 예약이 없어요</h3><p>새로운 프로그램을 둘러보세요.</p></div>}</div>}

function Ticket({selected,slot,qty,total,home}:any){return <div className="success-page"><Steps now={4}/><div className="success-icon">✓</div><h1>예약이 완료되었습니다!</h1><p>현장에서 아래 모바일 티켓을 보여주세요.</p><div className="ticket"><div className="ticket-top"><small>LET&apos;S RUN PLAY TICKET</small><span>예약 확정</span></div><div className={`ticket-art ${selected.tone}`}><b>{selected.icon}</b><span>{selected.region} LET&apos;S RUN PARK</span></div><div className="ticket-body"><small>{selected.region} 렛츠런파크</small><h2>{selected.title}</h2><div className="ticket-data"><div><small>이용일</small><b>2026.08.30 (일)</b></div><div><small>회차</small><b>{slot}</b></div><div><small>인원</small><b>{qty}명</b></div></div><div className="barcode">▌▌ ▌ ▌▌▌ ▌▌ ▌ ▌▌▌▌ ▌ ▌▌ ▌▌▌</div><code>R260826-143021</code></div><div className="ticket-foot"><span>결제금액 {money(total)}</span><span>이용 10분 전까지 취소 가능</span></div></div><div className="success-actions"><button onClick={home}>프로그램 더 보기</button><button className="primary" onClick={()=>window.print()}>티켓 저장하기</button></div></div>}

function Admin({tab,setTab,blocked,setBlocked,showToast}:any){const tabs=["대시보드","예약 관리","현장 검표","매출·정산","회차 관리"];return <div className="admin-shell"><aside className="admin-side"><div><b className="admin-logo">L</b><span>LET&apos;S RUN<br/><strong>예약 운영센터</strong></span></div><nav>{tabs.map((t,i)=><button key={t} className={tab===t?"on":""} onClick={()=>setTab(t)}><span>{["⌂","▤","▣","▥","◷"][i]}</span>{t}</button>)}</nav><div className="role"><small>현재 권한</small><b>서울 공원화사업팀TF</b><span>포니체험 전용</span></div></aside><section className="admin-main"><header><div><small>2026년 8월 26일 수요일</small><h1>{tab}</h1></div><div className="admin-user"><span>알림 3</span><b>오은주 관리자</b></div></header>{tab==="대시보드"&&<Dashboard setTab={setTab}/>} {tab==="예약 관리"&&<Reservations showToast={showToast}/>} {tab==="현장 검표"&&<Checkin showToast={showToast}/>} {tab==="매출·정산"&&<Settlement showToast={showToast}/>} {tab==="회차 관리"&&<Slots blocked={blocked} setBlocked={setBlocked} showToast={showToast}/>}</section></div>}
function Dashboard({setTab}:any){return <><div className="admin-alert"><span>☂</span><div><b>기상 악화 가능성이 있습니다</b><p>8월 30일 서울 지역 강수 확률 80% · 예약 14건을 확인해주세요.</p></div><button onClick={()=>setTab("예약 관리")}>예약 확인</button></div><div className="metrics">{[["오늘 예약","32건","전일 대비 +12%"],["오늘 매출","284,000원","결제완료 기준"],["이번 달 매출","8,420,000원","목표의 84%"],["오늘 잔여석","18석","온라인 배정 50%"]].map((m,i)=><article key={m[0]}><span className={`metric-icon c${i}`}>{["▤","₩","↗","◷"][i]}</span><small>{m[0]}</small><strong>{m[1]}</strong><p>{m[2]}</p></article>)}</div><div className="admin-grid"><section className="chart-card"><div className="card-heading"><div><h3>예약·매출 추이</h3><p>최근 7일 결제완료 기준</p></div><b>총 1,842,000원</b></div><div className="chart"><div className="ylabels"><span>40만</span><span>30만</span><span>20만</span><span>10만</span><span>0</span></div><div className="bars">{[42,58,48,75,62,88,70].map((h,i)=><div key={i}><span style={{height:`${h}%`}}></span><small>{20+i}일</small></div>)}</div></div></section><section className="rank-card"><div className="card-heading"><div><h3>프로그램별 예약</h3><p>이번 달 누적</p></div></div>{[["포니 승마체험",428,"43%"],["렛츠런파크 투어",296,"30%"],["제주마 승마체험",174,"17%"],["말 테마파크 투어",98,"10%"]].map((r,i)=><div className="rank" key={r[0]}><b>{i+1}</b><span>{r[0]}<i><em style={{width:r[2]}}></em></i></span><strong>{r[1]}건</strong></div>)}</section></div><section className="recent"><div className="card-heading"><div><h3>최근 예약</h3><p>예약일시로 빠르게 고객을 찾을 수 있어요.</p></div><button onClick={()=>setTab("예약 관리")}>전체보기 →</button></div><BookingTable rows={bookings.slice(0,3)}/></section></>}
function BookingTable({rows,actions}:any){return <div className="table-wrap"><table><thead><tr><th>예약일시</th><th>예약번호</th><th>고객</th><th>프로그램 / 이용일시</th><th>인원</th><th>결제금액</th><th>상태</th>{actions&&<th></th>}</tr></thead><tbody>{rows.map((b:any)=><tr key={b.no}><td><b>{b.booked}</b></td><td>{b.no}</td><td>{b.customer}<small>{b.phone}</small></td><td><b>{b.program}</b><small>{b.when}</small></td><td>{b.qty}명</td><td><b>{money(b.amount)}</b></td><td><span className={`pill ${b.status}`}>{b.status}</span></td>{actions&&<td><button onClick={()=>actions(b)}>상세</button></td>}</tr>)}</tbody></table></div>}
function Reservations({showToast}:any){const [query,setQuery]=useState("");const [selected,setSelected]=useState<any>(null);const rows=bookings.filter(b=>!query||Object.values(b).join(" ").includes(query));return <><div className="filter-card"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="예약일시, 예약번호로 검색"/></div><select><option>전체 상태</option><option>결제완료</option><option>이용완료</option><option>취소완료</option></select><select><option>전체 프로그램</option><option>포니 승마체험</option></select><button className="dark">조회</button></div><div className="result-head"><div><h3>전체 예약 <b>{rows.length}</b></h3><p>서울 공원화사업팀TF · 포니체험 조회 권한</p></div><button onClick={()=>showToast("예약 목록 엑셀을 생성했습니다")}>↓ 엑셀 다운로드</button></div><BookingTable rows={rows} actions={setSelected}/>{selected&&<div className="drawer-back" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="drawer-x" onClick={()=>setSelected(null)}>×</button><span className="pill 결제완료">{selected.status}</span><h2>예약 상세</h2><p className="drawer-id">{selected.no}</p><dl><div><dt>예약일시</dt><dd>{selected.booked}</dd></div><div><dt>고객</dt><dd>{selected.customer} · {selected.phone}</dd></div><div><dt>프로그램</dt><dd>{selected.program}</dd></div><div><dt>이용일시</dt><dd>{selected.when}</dd></div><div><dt>인원 / 결제</dt><dd>{selected.qty}명 · {money(selected.amount)}</dd></div></dl><button className="danger" onClick={()=>{showToast("환불 처리가 완료되었습니다");setSelected(null)}}>예약 취소 및 전액 환불</button></aside></div>}</>}
function Checkin({showToast}:any){const [done,setDone]=useState(false);return <div className="checkin"><div className="scan-box"><span>▣</span><h2>모바일 티켓을 스캔해주세요</h2><p>카메라 영역에 QR 또는 바코드를 맞춰주세요.</p><div className="scan-frame"><i></i><b>▥</b></div><button onClick={()=>setDone(true)}>예약번호로 직접 조회</button></div>{done&&<div className="check-result"><span>예약 확인</span><h2>포니 승마체험</h2><p>2026.08.30 (일) · 10:00</p><div><b>김렛츠</b><strong>2명</strong></div><button className="primary" onClick={()=>showToast("2명 검표 완료 처리했습니다")}>2명 모두 입장 처리</button></div>}</div>}
function Settlement({showToast}:any){return <><div className="metrics compact">{[["8월 총 결제","8,420,000원"],["환불","-324,000원"],["PG 수수료","-210,500원"],["정산 예정","7,885,500원"]].map((m,i)=><article key={m[0]}><small>{m[0]}</small><strong>{m[1]}</strong><p>{i===3?"월말 수동 정산":"2026.08.01—08.31"}</p></article>)}</div><section className="settle-card"><div className="card-heading"><div><h3>지역·부서·프로그램별 정산</h3><p>결제 파라미터 태깅 기준 · 단일 MID</p></div><div><button onClick={()=>showToast("정산서를 생성했습니다")}>정산서 PDF</button><button className="dark" onClick={()=>showToast("정산 엑셀을 생성했습니다")}>↓ 엑셀 다운로드</button></div></div><table><thead><tr><th>지역</th><th>담당 부서</th><th>프로그램</th><th>결제</th><th>환불</th><th>수수료</th><th>정산 예정액</th></tr></thead><tbody>{programs.map((p,i)=><tr key={p.id}><td><span className="region-dot">●</span>{p.region}</td><td>{p.dept}</td><td><b>{p.title}</b></td><td>{money(820000+i*133000)}</td><td>-{money(i*12000)}</td><td>-{money(20500+i*3100)}</td><td><b>{money(799500+i*117900)}</b></td></tr>)}</tbody></table></section></>}
function Slots({blocked,setBlocked,showToast}:any){const toggle=(s:string)=>{setBlocked((x:string[])=>x.includes(s)?x.filter(v=>v!==s):[...x,s]);showToast(xText(s,blocked.includes(s)))};return <><div className="slot-toolbar"><div><button>‹</button><b>2026년 8월 30일 일요일</b><button>›</button></div><select><option>서울 · 포니 승마체험</option></select><button className="dark" onClick={()=>showToast("새 회차 설정 창을 열었습니다")}>＋ 회차 추가</button></div><div className="inventory-note"><b>온라인 50%</b><span>총 40석 중 온라인 20석 · 현장 20석으로 분리 운영 중입니다.</span></div><div className="slot-cards">{slots.map((s,i)=>{const off=blocked.includes(s);return <article className={off?"blocked":""} key={s}><div className="slot-time"><small>{i<2?"오전":"오후"}</small><strong>{s}</strong></div><div className="capacity"><div><span>온라인 예약</span><b>{off?0:Math.max(0,8-i*2)} <small>/ 10석</small></b></div><i><em style={{width:off?"0%":`${80-i*15}%`}}></em></i><p><span>현장 배정 10석</span><span>{off?"고객 화면 미노출":`${i*2+2}석 남음`}</span></p></div><button className={off?"open":"close"} onClick={()=>toggle(s)}>{off?"차단 해제":"회차 차단"}</button></article>})}</div></>}
function xText(s:string,was:boolean){return `${s} 회차를 ${was?"다시 열었습니다":"차단했습니다"}`}
